name: LobbySystem
version: '${project.version}'
main: de.lauxmedia.avium.lobby.Lobby
api-version: 1.16
depend:
  - ProtocolLib
  - CoinsAPI
softdepend:
  - CloudNet-Bridge
authors: [ jonax, lauxmedia ]
website: lauxmedia.de
description: A lobby system for server networks.

commands:
  killall:
    description: Kill all entities.
  setspawn:
    description: Set spawn location.
  spawn:
    description: Teleport to spawn location.
  build:
    description: Change Build-Mode.
    usage: '§cPlease use: /build <player>'
  setwarp:
    description: Set a warp.
    usage: '§cPlease use: /setwarp <name>'
  warp:
    description: Set a warp.
    usage: '§cPlease use: /warp <name>'
  createnpc:
    description: Create a NPC.
    usage: '§cPlease use: /createnpc <skinOwner> <displayName>'
  editnpc:
    description: Create a NPC.
    usage: '§cPlease use: /editnpc <arg> <arg>'
  coins:
    description: add, set or remove coins.
    usage: '§cPlease use: /coins'